# services:
#   - type: web
#     name: mysite
#     env: python
#     buildCommand: ""
#     startCommand: gunicorn portfolio.wsgi:application --log-file -
#     envVars:
#       - key: DJANGO_SETTINGS_MODULE
#         value: mysite.settings
#       - key: SECRET_KEY
#         sync: false
# # render.yaml

services:
  - name: web
    envVars:
      - key: DJANGO_ENVIRONMENT
        value: production
    # buildCommand: bash setup.sh
    startCommand: gunicorn mysite.wsgi --bind 0.0.0.0:$PORT
    buildCommand: ./setup.sh


